user nginx;

events {
	worker_connections 1024;
}

http {
	include /etc/nginx/mime.types;
	server {
		listen 3000;
		listen [::]:3000;

		root /app/public/;
		index index.html;
		location / {
		}
	}
	server {
		listen 3091;
		listen [::]:3091;

		location /status/ {
			stub_status;
		}
	}
}
