FROM node:22

#Create a app directory
WORKDIR /app-back

#Install app depedencies
COPY backend/package*.json ./

#Run npm install
RUN npm install

#Bundle app source
COPY backend/ ./

EXPOSE 3001               
#${PORT_BACK}

CMD [ "npm", "run", "dev" ]