{
 "title": "services_up",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "webserv",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "{\"nginx-webservIsUp\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "frontend",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "{\"nginx-frontendIsUp\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "nginx_exporter-webserv",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "{\"nginx_prometheus_exporter-webservIsUp\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "nginx_exporter-frontend",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "{\"nginx_prometheus_exporter-frontendIsUp\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "backend",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "{\"backendIsUp\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ponggame",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "{\"ponggameIsUp\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "prometheus",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "{\"prometheusIsUp\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "grafana",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "{\"grafanaIsUp\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "node_exporter",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "{\"node_exporterIsUp\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "services_up",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    { "expr": "backendIsUp", "legendFormat": "backend" },
    { "expr": "grafanaIsUp", "legendFormat": "grafana" },
    { "expr": "prometheusIsUp", "legendFormat": "prometheus" },
    { "expr": "node_exporterIsUp", "legendFormat": "node_exporter" },
    {
     "expr": "{\"nginx-webservIsUp\"}",
     "legendFormat": "webserv"
    },
    {
     "expr": "{\"nginx-frontendIsUp\"}",
     "legendFormat": "frontend"
    },
    {
     "expr": "{\"nginx_prometheus_exporter-webservIsUp\"}",
     "legendFormat": "nginx_exporter-webserv"
    },
    {
     "expr": "{\"nginx_prometheus_exporter-frontendIsUp\"}",
     "legendFormat": "nginx_exporter-frontend"
    },
    { "expr": "ponggameIsUp", "legendFormat": "ponggame" },
    {}
   ]
  }
 ]
}