user nginx;

events {
	worker_connections 1024;
}

http {
	ssl_protocols TLSv1.3;
	ssl_certificate /var/cert.pem;
	ssl_certificate_key /var/key.pem;

	add_header X-Clacks-Overhead "GNU Terry Pratchett";
	server {
		listen 3443 ssl;
		listen [::]:3443 ssl;

		location / {
			# proxy_set_header Host $http_host;
			proxy_pass http://frontend:3000/;
		}
		location /api/ {
			proxy_set_header Host $http_host;
			proxy_pass http://backend:3001/;
		}
		location /api/game/ {
			proxy_set_header Host $http_host;
			proxy_pass http://ponggame:3002/api/game/;
		}
		location /socket.io/ {
		    proxy_pass http://ponggame:3002;
		    proxy_http_version 1.1;
		    proxy_set_header Upgrade $http_upgrade;
		    proxy_set_header Connection "upgrade";
		    proxy_set_header Host $http_host;
		}
	}
	server {
		listen 3444 ssl;
		listen [::]:3444 ssl;

		location / {
			proxy_set_header Host $http_host;
			proxy_pass http://grafana:3030/;
		}
	}
	server {
		listen 3446;
		listen [::]:3446;

		location /status/ {
			stub_status;
		}
	}
}
